import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signOut } from "next-auth/react";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Authentication
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {!session && (
              <>
                <Link
                  className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                  href="/auth/login"
                  target=""
                >
                  <h3 className="text-2xl font-bold">Đăng Nhập</h3>
                </Link>
                <Link
                  className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                  href="/auth/register"
                >
                  <h3 className="text-2xl font-bold">Đăng Kí</h3>
                </Link>
              </>
            )}
            {session && (
              <>
                <h3 className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-2xl font-bold text-white hover:bg-white/20">
                  {session.user.email}
                </h3>
                <button
                  className="flex items-center font-bold text-2xl max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                  onClick={() => signOut()}
                >
                  Sign out
                </button>
                {session.user.role === "ADMIN" && (
                  <Link
                    className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                    href="/dashboard"
                  >
                    <h3 className="text-2xl font-bold">Dashboard</h3>
                  </Link>
                )}
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
